# Generated by Django 5.1.3 on 2024-12-04 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0003_cookingmethod_diet_recipecategory_recipe_diet_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='diet',
        ),
        migrations.AddField(
            model_name='recipe',
            name='diet',
            field=models.ManyToManyField(null=True, related_name='recipes', to='generator.diet'),
        ),
    ]
