# Generated by Django 5.1.3 on 2024-12-04 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0004_remove_recipe_diet_recipe_diet'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='diet',
            new_name='diets',
        ),
    ]
