# Generated by Django 5.1.3 on 2024-12-05 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0005_rename_diet_recipe_diets'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recipe',
            options={'ordering': ['created_at']},
        ),
        migrations.AddField(
            model_name='recipe',
            name='cooking_methods',
            field=models.ManyToManyField(related_name='recipes', to='generator.cookingmethod'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='diets',
            field=models.ManyToManyField(related_name='recipes', to='generator.diet'),
        ),
    ]
