# Generated by Django 5.1.3 on 2024-12-05 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0006_alter_recipe_options_recipe_cooking_methods_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='spiciness',
            field=models.IntegerField(choices=[(0, 'Unknown'), (1, 'Not Spicy'), (2, 'Mild'), (3, 'Medium'), (4, 'Hot')], default=0),
        ),
    ]
