# Generated by Django 5.1.3 on 2024-12-05 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0007_recipe_spiciness'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='cost',
            field=models.IntegerField(choices=[(0, 'Unkown'), (1, 'Budget'), (2, 'Moderate'), (3, 'Mid-Range'), (4, 'Premium')], default=0),
        ),
    ]
