# Generated by Django 5.1.3 on 2024-12-05 10:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0008_recipe_cost'),
    ]

    operations = [
        migrations.CreateModel(
            name='CuisineSubtype',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=99)),
            ],
        ),
        migrations.CreateModel(
            name='CuisineType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=99)),
            ],
        ),
        migrations.AddField(
            model_name='recipe',
            name='storage',
            field=models.TextField(default=' '),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='recipe',
            name='cost',
            field=models.IntegerField(choices=[(0, 'Not Specified'), (1, 'Budget'), (2, 'Moderate'), (3, 'Mid-Range'), (4, 'Premium')], default=0),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='default_servings',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='recipe',
            name='difficulty',
            field=models.IntegerField(choices=[(0, 'Not Specified'), (1, 'Beginner'), (2, 'Intermediate'), (3, 'Advanced'), (4, 'Expert')], default=0),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='spiciness',
            field=models.IntegerField(choices=[(0, 'Not Specified'), (1, 'Not Spicy'), (2, 'Mild'), (3, 'Medium'), (4, 'Hot')], default=0),
        ),
        migrations.AddField(
            model_name='recipe',
            name='cuisine_subtypes',
            field=models.ManyToManyField(related_name='recipes', to='generator.cuisinesubtype'),
        ),
        migrations.AddField(
            model_name='cuisinesubtype',
            name='cuisine_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subtypes', to='generator.cuisinetype'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='cuisine_types',
            field=models.ManyToManyField(related_name='recipes', to='generator.cuisinetype'),
        ),
    ]
