# Generated by Django 5.1.3 on 2024-12-05 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0009_cuisinesubtype_cuisinetype_recipe_storage_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hashtag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='cuisinesubtype',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='cuisinetype',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AddField(
            model_name='recipe',
            name='hashtags',
            field=models.ManyToManyField(related_name='recipes', to='generator.hashtag'),
        ),
    ]
