# Generated by Django 5.1.3 on 2024-12-05 14:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CookingMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('name_en', models.CharField(max_length=50, null=True)),
                ('name_de', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CuisineType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('name_en', models.CharField(max_length=50, null=True)),
                ('name_de', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Diet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('name_en', models.CharField(max_length=50, null=True)),
                ('name_de', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Hashtag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('name_en', models.CharField(max_length=50, null=True)),
                ('name_de', models.CharField(max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='IngredientCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('name_en', models.CharField(max_length=50, null=True)),
                ('name_de', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='RecipeCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('name_en', models.CharField(max_length=50, null=True)),
                ('name_de', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CuisineSubtype',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('name_en', models.CharField(max_length=50, null=True)),
                ('name_de', models.CharField(max_length=50, null=True)),
                ('cuisine_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subtypes', to='recipes.cuisinetype')),
            ],
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('name_en', models.CharField(max_length=50, null=True)),
                ('name_de', models.CharField(max_length=50, null=True)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='recipes.ingredientcategory')),
            ],
            options={
                'ordering': ['category'],
            },
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('title_en', models.CharField(max_length=255, null=True)),
                ('title_de', models.CharField(max_length=255, null=True)),
                ('description', models.TextField()),
                ('description_en', models.TextField(null=True)),
                ('description_de', models.TextField(null=True)),
                ('difficulty', models.IntegerField(choices=[(0, 'Not Specified'), (1, 'Beginner'), (2, 'Intermediate'), (3, 'Advanced'), (4, 'Expert')], default=0)),
                ('time_total', models.IntegerField()),
                ('time_preparation', models.IntegerField()),
                ('time_cooking', models.IntegerField()),
                ('default_servings', models.IntegerField()),
                ('storage', models.TextField()),
                ('storage_en', models.TextField(null=True)),
                ('storage_de', models.TextField(null=True)),
                ('cost', models.IntegerField(choices=[(0, 'Not Specified'), (1, 'Budget'), (2, 'Moderate'), (3, 'Mid-Range'), (4, 'Premium')], default=0)),
                ('spiciness', models.IntegerField(choices=[(0, 'Not Specified'), (1, 'Not Spicy'), (2, 'Mild'), (3, 'Medium'), (4, 'Hot')], default=0)),
                ('created_by', models.CharField(default='Claude', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cooking_methods', models.ManyToManyField(related_name='recipes', to='recipes.cookingmethod')),
                ('cuisine_subtypes', models.ManyToManyField(related_name='recipes', to='recipes.cuisinesubtype')),
                ('cuisine_types', models.ManyToManyField(related_name='recipes', to='recipes.cuisinetype')),
                ('diets', models.ManyToManyField(related_name='recipes', to='recipes.diet')),
                ('hashtags', models.ManyToManyField(related_name='recipes', to='recipes.hashtag')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recipes', to='recipes.recipecategory')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='RecipeIngredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('M', 'Main Ingredient'), ('A', 'Additional Ingredient')], max_length=25)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=7)),
                ('unit', models.CharField(max_length=25)),
                ('note', models.CharField(max_length=255)),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipes', to='recipes.ingredient')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredients', to='recipes.recipe')),
            ],
            options={
                'ordering': ['recipe', 'type', 'ingredient'],
            },
        ),
        migrations.CreateModel(
            name='RecipeInstruction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('headline', models.CharField(max_length=50)),
                ('headline_en', models.CharField(max_length=50, null=True)),
                ('headline_de', models.CharField(max_length=50, null=True)),
                ('description', models.TextField()),
                ('description_en', models.TextField(null=True)),
                ('description_de', models.TextField(null=True)),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instruction_steps', to='recipes.recipe')),
            ],
            options={
                'ordering': ['recipe', 'number'],
            },
        ),
    ]
