# Generated by Django 5.1.3 on 2024-12-05 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cookingmethod',
            name='name_de',
        ),
        migrations.RemoveField(
            model_name='cookingmethod',
            name='name_en',
        ),
        migrations.RemoveField(
            model_name='cuisinesubtype',
            name='name_de',
        ),
        migrations.RemoveField(
            model_name='cuisinesubtype',
            name='name_en',
        ),
        migrations.RemoveField(
            model_name='cuisinetype',
            name='name_de',
        ),
        migrations.RemoveField(
            model_name='cuisinetype',
            name='name_en',
        ),
        migrations.RemoveField(
            model_name='diet',
            name='name_de',
        ),
        migrations.RemoveField(
            model_name='diet',
            name='name_en',
        ),
        migrations.RemoveField(
            model_name='hashtag',
            name='name_de',
        ),
        migrations.RemoveField(
            model_name='hashtag',
            name='name_en',
        ),
        migrations.RemoveField(
            model_name='ingredient',
            name='name_de',
        ),
        migrations.RemoveField(
            model_name='ingredient',
            name='name_en',
        ),
        migrations.RemoveField(
            model_name='ingredientcategory',
            name='name_de',
        ),
        migrations.RemoveField(
            model_name='ingredientcategory',
            name='name_en',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='description_de',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='description_en',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='storage_de',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='storage_en',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='title_de',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='title_en',
        ),
        migrations.RemoveField(
            model_name='recipecategory',
            name='name_de',
        ),
        migrations.RemoveField(
            model_name='recipecategory',
            name='name_en',
        ),
        migrations.RemoveField(
            model_name='recipeinstruction',
            name='description_de',
        ),
        migrations.RemoveField(
            model_name='recipeinstruction',
            name='description_en',
        ),
        migrations.RemoveField(
            model_name='recipeinstruction',
            name='headline_de',
        ),
        migrations.RemoveField(
            model_name='recipeinstruction',
            name='headline_en',
        ),
    ]
