# Generated by Django 5.1.3 on 2024-12-13 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='time_active',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='time_inactive',
        ),
    ]
