# Generated by Django 5.1.3 on 2024-12-18 07:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_remove_recipe_time_active_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='difficulty',
            field=models.IntegerField(choices=[(1, 'Simpel'), (2, 'Fortgeschritten'), (3, 'Anspruchsvoll')], verbose_name='Schwierigkeitsgrad'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='spiciness',
            field=models.IntegerField(choices=[(0, 'Nicht Scharf'), (1, 'Leicht scharf'), (2, 'Mittelscharf'), (3, 'Sehr scharf')], default=0, verbose_name='Schärfe'),
        ),
        migrations.AlterField(
            model_name='recipetime',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='times', to='recipes.recipe'),
        ),
        migrations.AddConstraint(
            model_name='reciperating',
            constraint=models.UniqueConstraint(fields=('recipe', 'author'), name='unique_rating'),
        ),
    ]
