# Generated by Django 5.1.3 on 2024-12-05 17:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_remove_cookingmethod_name_de_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=2)),
                ('name', models.CharField(max_length=255, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='hashtag',
            name='created_at',
        ),
        migrations.AddField(
            model_name='cookingmethod',
            name='language',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='recipes.language'),
        ),
        migrations.AddField(
            model_name='cuisinesubtype',
            name='language',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='recipes.language'),
        ),
        migrations.AddField(
            model_name='cuisinetype',
            name='language',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='recipes.language'),
        ),
        migrations.AddField(
            model_name='diet',
            name='language',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='recipes.language'),
        ),
        migrations.AddField(
            model_name='hashtag',
            name='language',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='recipes.language'),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='language',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='recipes.language'),
        ),
        migrations.AddField(
            model_name='ingredientcategory',
            name='language',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='recipes.language'),
        ),
        migrations.AddField(
            model_name='recipecategory',
            name='language',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='recipes.language'),
        ),
        migrations.AddField(
            model_name='recipeingredient',
            name='language',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='recipes.language'),
        ),
        migrations.AddField(
            model_name='recipeinstruction',
            name='language',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='recipes.language'),
        ),
    ]
