# Generated by Django 5.1.3 on 2024-12-05 18:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_language_remove_hashtag_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='language',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='recipes.language'),
        ),
    ]
