# Generated by Django 5.1.3 on 2024-12-06 09:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_recipe_language'),
    ]

    operations = [
        migrations.CreateModel(
            name='Beverage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('language', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='recipes.language')),
            ],
        ),
        migrations.AddField(
            model_name='recipe',
            name='beverage_recommendation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='recipes.beverage'),
        ),
        migrations.CreateModel(
            name='BeverageType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('language', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='recipes.language')),
            ],
        ),
        migrations.AddField(
            model_name='beverage',
            name='type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='recipes.beveragetype'),
        ),
        migrations.CreateModel(
            name='RecipeAdditionalIngredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=7)),
                ('unit', models.CharField(max_length=25)),
                ('note', models.CharField(max_length=255)),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipes_additional', to='recipes.ingredient')),
                ('language', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='recipes.language')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='additional_ingredients', to='recipes.recipe')),
            ],
            options={
                'ordering': ['recipe', 'ingredient'],
            },
        ),
        migrations.CreateModel(
            name='RecipeMainIngredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=7)),
                ('unit', models.CharField(max_length=25)),
                ('note', models.CharField(max_length=255)),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipes_main', to='recipes.ingredient')),
                ('language', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='recipes.language')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='main_ingredients', to='recipes.recipe')),
            ],
            options={
                'ordering': ['recipe', 'ingredient'],
            },
        ),
        migrations.DeleteModel(
            name='RecipeIngredient',
        ),
    ]
