# Generated by Django 5.1.3 on 2024-12-06 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0005_beverage_recipe_beverage_recommendation_beveragetype_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='time_cooking',
            new_name='time_active',
        ),
        migrations.RenameField(
            model_name='recipe',
            old_name='time_preparation',
            new_name='time_inactive',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='time_total',
        ),
        migrations.AlterField(
            model_name='recipe',
            name='difficulty',
            field=models.IntegerField(choices=[(0, 'Not Specified'), (1, 'Easy'), (2, 'Advanced'), (3, 'Expert')], default=0),
        ),
    ]
