# Generated by Django 5.1.3 on 2024-12-20 09:50

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0005_shoppingrecipes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ShoppingRecipes',
            new_name='ShoppingRecipe',
        ),
    ]
