# Generated by Django 5.1.3 on 2024-12-23 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0006_rename_shoppingrecipes_shoppingrecipe'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='beverage',
        ),
        migrations.RemoveField(
            model_name='beveragetype',
            name='language',
        ),
        migrations.RemoveField(
            model_name='cookingmethod',
            name='language',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='cooking_methods',
        ),
        migrations.RemoveField(
            model_name='cuisinetype',
            name='language',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='cuisine_types',
        ),
        migrations.RemoveField(
            model_name='recipecategory',
            name='language',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='category',
        ),
        migrations.DeleteModel(
            name='Beverage',
        ),
        migrations.DeleteModel(
            name='BeverageType',
        ),
        migrations.DeleteModel(
            name='CookingMethod',
        ),
        migrations.DeleteModel(
            name='CuisineType',
        ),
        migrations.DeleteModel(
            name='RecipeCategory',
        ),
    ]
