# Generated by Django 5.1.3 on 2024-12-06 11:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0006_rename_time_cooking_recipe_time_active_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecipeTip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tip', models.TextField()),
                ('language', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='recipes.language')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tips', to='recipes.recipe')),
            ],
            options={
                'ordering': ['recipe'],
            },
        ),
    ]
