# Generated by Django 5.1.3 on 2024-12-06 14:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0007_recipetip'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipemainingredient',
            name='ingredient',
        ),
        migrations.RemoveField(
            model_name='recipemainingredient',
            name='language',
        ),
        migrations.RemoveField(
            model_name='recipemainingredient',
            name='recipe',
        ),
        migrations.CreateModel(
            name='RecipeComponent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='components', to='recipes.recipe')),
            ],
        ),
        migrations.CreateModel(
            name='ComponentIngredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=7)),
                ('unit', models.CharField(max_length=25)),
                ('note', models.CharField(max_length=50)),
                ('item', models.CharField(max_length=50)),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commponents', to='recipes.ingredient')),
                ('language', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='recipes.language')),
                ('recipe_component', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredients', to='recipes.recipecomponent')),
            ],
            options={
                'ordering': ['recipe_component', 'ingredient'],
            },
        ),
        migrations.DeleteModel(
            name='RecipeAdditionalIngredient',
        ),
        migrations.DeleteModel(
            name='RecipeMainIngredient',
        ),
    ]
