# Generated by Django 5.1.3 on 2024-12-08 10:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0008_remove_recipemainingredient_ingredient_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='created_by',
            new_name='author',
        ),
        migrations.AlterField(
            model_name='recipe',
            name='beverage_recommendation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='recipes.beverage'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='cooking_methods',
            field=models.ManyToManyField(blank=True, related_name='recipes', to='recipes.cookingmethod'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='cuisine_subtypes',
            field=models.ManyToManyField(blank=True, null=True, related_name='recipes', to='recipes.cuisinesubtype'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='cuisine_types',
            field=models.ManyToManyField(blank=True, null=True, related_name='recipes', to='recipes.cuisinetype'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='diets',
            field=models.ManyToManyField(blank=True, null=True, related_name='recipes', to='recipes.diet'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='difficulty',
            field=models.IntegerField(choices=[(0, 'Not Specified'), (1, 'Einfach'), (2, 'Fortgeschritten'), (3, 'Profi'), (4, 'Michelin')], default=0),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='hashtags',
            field=models.ManyToManyField(blank=True, related_name='recipes', to='recipes.hashtag'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='storage',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='time_inactive',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
