# Generated by Django 5.1.3 on 2024-12-08 12:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0009_rename_created_by_recipe_author_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recipe',
            options={'ordering': ['difficulty']},
        ),
        migrations.AlterField(
            model_name='recipe',
            name='cuisine_subtypes',
            field=models.ManyToManyField(blank=True, related_name='recipes', to='recipes.cuisinesubtype'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='cuisine_types',
            field=models.ManyToManyField(blank=True, related_name='recipes', to='recipes.cuisinetype'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='diets',
            field=models.ManyToManyField(blank=True, related_name='recipes', to='recipes.diet'),
        ),
        migrations.CreateModel(
            name='RecipeImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alt_text', models.CharField(blank=True, default='recipe image', max_length=100)),
                ('upload_datetime', models.DateTimeField(auto_now_add=True)),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='image', to='recipes.recipe')),
            ],
            options={
                'ordering': ['-upload_datetime'],
            },
        ),
    ]
