# Generated by Django 5.1.3 on 2024-12-08 13:16

import recipes.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0010_alter_recipe_options_alter_recipe_cuisine_subtypes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipeimage',
            name='image',
            field=models.ImageField(blank=True, max_length=500, null=True, storage=recipes.models.ImageStorage(), upload_to='recipe_images/'),
        ),
    ]
