# Generated by Django 5.1.3 on 2024-12-08 17:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0011_recipeimage_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='author',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='difficulty',
            field=models.IntegerField(choices=[(0, 'Not Specified'), (1, 'Einfach'), (2, 'Fortgeschritten'), (3, 'Profi'), (4, 'Sterneküche')], default=0),
        ),
        migrations.AlterField(
            model_name='recipeimage',
            name='recipe',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='image', to='recipes.recipe'),
        ),
    ]
