# Generated by Django 5.1.3 on 2024-12-11 17:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0014_alter_reciperating_rating_savedrecipe'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recipes', to=settings.AUTH_USER_MODEL, verbose_name='Autor'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recipes', to='recipes.recipecategory', verbose_name='Kategorie'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='cuisine_subtypes',
            field=models.ManyToManyField(blank=True, related_name='recipes', to='recipes.cuisinesubtype', verbose_name='Küche Unterkategorie'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='cuisine_types',
            field=models.ManyToManyField(blank=True, related_name='recipes', to='recipes.cuisinetype', verbose_name='Küche'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='default_servings',
            field=models.IntegerField(verbose_name='Portionen'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Kurzbeschreibung'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='diets',
            field=models.ManyToManyField(blank=True, related_name='recipes', to='recipes.diet', verbose_name='Ernährungsweise'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='difficulty',
            field=models.IntegerField(choices=[(0, 'Not Specified'), (1, 'Simpel'), (2, 'Ambitioniert'), (3, 'Gourmet'), (4, 'Avantgarde')], default=0, verbose_name='Schwierigkeitsgrad'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='storage',
            field=models.TextField(blank=True, null=True, verbose_name='Aufbewahrung'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='time_active',
            field=models.IntegerField(verbose_name='Aktive Zeit (Min.)'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='time_inactive',
            field=models.IntegerField(blank=True, default=0, verbose_name='Inakive Zeit (Min.)'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Titel'),
        ),
    ]
