# Generated by Django 5.1.3 on 2024-12-11 17:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0015_alter_recipe_author_alter_recipe_category_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='cuisine_subtypes',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='beverage_recommendation',
        ),
        migrations.AddField(
            model_name='recipe',
            name='beverage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='recipes.beverage', verbose_name='Getränkeempfehlung'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='cooking_methods',
            field=models.ManyToManyField(blank=True, related_name='recipes', to='recipes.cookingmethod', verbose_name='Techniken'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='cost',
            field=models.IntegerField(choices=[(0, 'Not Specified'), (1, 'Budget'), (2, 'Moderate'), (3, 'Mid-Range'), (4, 'Premium')], default=0, verbose_name='Kosten'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='hashtags',
            field=models.ManyToManyField(blank=True, related_name='recipes', to='recipes.hashtag', verbose_name='Hashtags'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='language',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='recipes.language', verbose_name='Sprache'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='spiciness',
            field=models.IntegerField(choices=[(0, 'Not Specified'), (1, 'Not Spicy'), (2, 'Mild'), (3, 'Medium'), (4, 'Hot')], default=0, verbose_name='Schärfe'),
        ),
        migrations.DeleteModel(
            name='CuisineSubtype',
        ),
    ]
