# Generated by Django 5.1.3 on 2024-12-11 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0016_remove_recipe_cuisine_subtypes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='cost',
            field=models.IntegerField(choices=[(0, 'Not Specified'), (1, 'Günstig'), (2, 'Mittel'), (3, 'Teuer')], default=0, verbose_name='Kosten'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='difficulty',
            field=models.IntegerField(choices=[(1, 'Simpel'), (2, 'Ambitioniert'), (3, 'Gourmet')], verbose_name='Schwierigkeitsgrad'),
        ),
    ]
