# Generated by Django 5.1.3 on 2024-12-13 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0017_alter_recipe_cost_alter_recipe_difficulty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='difficulty',
            field=models.IntegerField(choices=[(1, 'Simpel'), (2, 'Ambitioniert'), (3, 'Anspruchsvoll')], verbose_name='Schwierigkeitsgrad'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='spiciness',
            field=models.IntegerField(choices=[(0, 'Not Spicy'), (1, 'Mild'), (2, 'Medium'), (3, 'Hot')], default=0, verbose_name='Schärfe'),
        ),
    ]
