# Generated by Django 5.1.3 on 2024-12-13 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chefs', '0002_profile_is_alpha_tester'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='chef_level',
            field=models.IntegerField(choices=[(0, 'Tellerwäscher'), (1, 'Chef de Partie'), (2, 'Sous Chef'), (3, 'Chef de Cuisine')], default=0, max_length=50),
        ),
    ]
