# Generated by Django 5.1.3 on 2024-12-13 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chefs', '0003_profile_chef_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='chef_level',
            field=models.IntegerField(choices=[(0, 'Tellerwäscher'), (1, 'Chef de Partie'), (2, 'Sous Chef'), (3, 'Chef de Cuisine')], default=0),
        ),
    ]
