# Generated by Django 5.1.3 on 2024-12-24 11:54

import chefs.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chefs', '0005_remove_profile_followers_profile_following'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, max_length=500, null=True, storage=chefs.models.ImageStorage(), upload_to='profile_images/')),
                ('alt_text', models.CharField(blank=True, default='profile image', max_length=100)),
                ('upload_datetime', models.DateTimeField(auto_now_add=True)),
                ('chef', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='image', to='chefs.profile')),
            ],
            options={
                'ordering': ['-upload_datetime'],
            },
        ),
    ]
