services:
  web:
    build:
      context: ../../
      dockerfile: docker/staging/Dockerfile
    user: "${USER_ID:-$(id -u)}:${GROUP_ID:-$(id -g)}"
    command: >
      gunicorn recipe_app.wsgi:application
      --bind 0.0.0.0:8000
      --timeout 120
      --threads 2
      --forwarded-allow-ips="*"
    restart: always
    ports:
      - "80:8000"
    environment:
      - SECRET_KEY=${SECRET_KEY}
    volumes:
      - ../../logs:/app/logs
      - ../../recipe_app/db.sqlite3:/app/recipe_app/db.sqlite3