services:
  web:
    build:
      context: ../../
      dockerfile: docker/staging/Dockerfile
    command: >
      gunicorn music_game_app.wsgi:application
      --bind 0.0.0.0:8000
      --forwarded-allow-ips="*"
    ports:
      - "80:8000"
    environment:
      - SECRET_KEY=${SECRET_KEY}