services:
  web-chatrcp:
    container_name: web-chatrcp
    build:
      context: ../../
      dockerfile: docker/staging/Dockerfile
    user: "1002:1002"
    command: >
      gunicorn recipe_app.wsgi:application
      --bind 0.0.0.0:8000
      --timeout 120
      --threads 2
      --forwarded-allow-ips="*"
    restart: always
    ports:
      - "3000:8000"
    environment:
      - SECRET_KEY=${SECRET_KEY}
    volumes:
      - ../../logs:/app/logs
      - ../../recipe_app/db.sqlite3:/app/recipe_app/db.sqlite3